DROP TABLE IF EXISTS user
DROP TABLE IF EXISTS userDetails
DROP TABLE IF EXISTS userRole
DROP TABLE IF EXISTS course
DROP TABLE IF EXISTS category
DROP TABLE IF EXISTS courseModule
DROP TABLE IF EXISTS lectures
DROP TABLE IF EXISTS assignment
DROP TABLE IF EXISTS assignment_file
DROP TABLE IF EXISTS subscribe

