// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Assignment struct {
	AssignmentID   int64         `json:"assignment_id"`
	UserID         sql.NullInt64 `json:"user_id"`
	CourseModuleID sql.NullInt64 `json:"course_module_id"`
	LectureID      sql.NullInt64 `json:"lecture_id"`
}

type AssignmentFile struct {
	AssignmentFileID int64         `json:"assignment_file_id"`
	AssignmentID     sql.NullInt64 `json:"assignment_id"`
	AssignmentLink   string        `json:"assignment_link"`
}

type Category struct {
	CategoryID   int64  `json:"category_id"`
	CategoryName string `json:"category_name"`
	CategoryDesc string `json:"category_desc"`
}

type Course struct {
	CourseID   int64  `json:"course_id"`
	CourseName string `json:"course_name"`
	CourseDesc string `json:"course_desc"`
	Category   string `json:"category"`
}

type CourseModule struct {
	ModuleID   int64         `json:"module_id"`
	CourseID   sql.NullInt64 `json:"course_id"`
	ModuleName string        `json:"module_name"`
}

type Lecture struct {
	LectureID      int64         `json:"lecture_id"`
	CourseModuleID sql.NullInt64 `json:"course_module_id"`
	LectureDesc    string        `json:"lecture_desc"`
	LectureNumber  sql.NullInt32 `json:"lecture_number"`
	VideoURL       string        `json:"video_URL"`
	Status         string        `json:"status"`
}

type Subscribe struct {
	SubscribeID int64         `json:"subscribe_id"`
	UserID      sql.NullInt64 `json:"user_id"`
	CourseID    sql.NullInt64 `json:"course_id"`
}

type User struct {
	UserID    int64  `json:"user_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Role      string `json:"role"`
}

type UserDetail struct {
	UserDetailsID int64         `json:"user_details_id"`
	UserID        sql.NullInt64 `json:"user_ID"`
	Phone         int32         `json:"phone"`
	AddressLine1  string        `json:"address_line1"`
	AddressLine2  string        `json:"address_line2"`
}

type UserRole struct {
	RoleID int64  `json:"role_id"`
	Role   string `json:"role"`
}
