// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: subscribe.sql

package db

import (
	"context"
	"database/sql"
)

const createSubscribe = `-- name: CreateSubscribe :one
INSERT INTO "subscribe"(
    user_id,
    course_id
) VALUES (
    $1, $2
)
RETURNING subscribe_id, user_id, course_id
`

type CreateSubscribeParams struct {
	UserID   sql.NullInt64 `json:"user_id"`
	CourseID sql.NullInt64 `json:"course_id"`
}

func (q *Queries) CreateSubscribe(ctx context.Context, arg CreateSubscribeParams) (Subscribe, error) {
	row := q.db.QueryRowContext(ctx, createSubscribe, arg.UserID, arg.CourseID)
	var i Subscribe
	err := row.Scan(&i.SubscribeID, &i.UserID, &i.CourseID)
	return i, err
}
